### PR TITLE
Update Go dependencies

### PR DESCRIPTION
**Pull request by macedogm**
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

### CODE REVIEW

**Review by MbolotSuse — DISMISSED** [review]
LGTM

**Comment by MbolotSuse** [comment]
Accidentally approved - don't merge yet

**Comment by macedogm** [comment]
@MbolotSuse not sure if you approved it and revert, but in case affirmative, we need the approval again in order to merge it, please.

**Review by MbolotSuse — APPROVED** [review]
Basic test case worked, so LGTM.

**Pull request merged**
